// Generated by uv run sprites bundle. Do not edit by hand.
import catalog from "../../assets/sprites/catalog.json";
import type { SpriteCatalog } from "./types";

export const spriteCatalog = catalog as unknown as SpriteCatalog;
export const spriteImages: Record<string, number> = {
  "barbarian_player/idle": require("../../assets/sprites/barbarian_player--idle.png"),
  "barbarian_player/walk": require("../../assets/sprites/barbarian_player--walk.png"),
  "barbarian_player/attack": require("../../assets/sprites/barbarian_player--attack.png"),
  "barbarian_player/death": require("../../assets/sprites/barbarian_player--death.png"),
  "bog_toad/idle": require("../../assets/sprites/bog_toad--idle.png"),
  "bog_toad/walk": require("../../assets/sprites/bog_toad--walk.png"),
  "bog_toad/attack": require("../../assets/sprites/bog_toad--attack.png"),
  "bog_toad/death": require("../../assets/sprites/bog_toad--death.png"),
  "drowned_corpse/idle": require("../../assets/sprites/drowned_corpse--idle.png"),
  "drowned_corpse/walk": require("../../assets/sprites/drowned_corpse--walk.png"),
  "drowned_corpse/attack": require("../../assets/sprites/drowned_corpse--attack.png"),
  "drowned_corpse/death": require("../../assets/sprites/drowned_corpse--death.png"),
  "bog_hag/idle": require("../../assets/sprites/bog_hag--idle.png"),
  "bog_hag/walk": require("../../assets/sprites/bog_hag--walk.png"),
  "bog_hag/attack": require("../../assets/sprites/bog_hag--attack.png"),
  "bog_hag/death": require("../../assets/sprites/bog_hag--death.png"),
  "root_hulk/idle": require("../../assets/sprites/root_hulk--idle.png"),
  "root_hulk/walk": require("../../assets/sprites/root_hulk--walk.png"),
  "root_hulk/attack": require("../../assets/sprites/root_hulk--attack.png"),
  "root_hulk/death": require("../../assets/sprites/root_hulk--death.png"),
  "giant_water_strider/idle": require("../../assets/sprites/giant_water_strider--idle.png"),
  "giant_water_strider/walk": require("../../assets/sprites/giant_water_strider--walk.png"),
  "giant_water_strider/attack": require("../../assets/sprites/giant_water_strider--attack.png"),
  "giant_water_strider/death": require("../../assets/sprites/giant_water_strider--death.png"),
};
